---

- name: my test installation
  hosts: localhost
  user: ubuntu
  become: true

  tasks:
  - name: update packages
    shell:
        cmd:  apt-get update
  - name: install certificate
    shell:
      cmd: apt-get install -y apt-transport-https ca-certificates curl
  - name: download public signing key
    shell:
      cmd: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - name: add kubernetess into apt repo
    shell:
      cmd: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - name: update packages
    shell:
      cmd: apt-get update
  - name: install kubectl
    shell:
      cmd: apt-get install -y kubectl