---

- name: minikube installation book
  hosts: localhost
  user: ubuntu
  become: true

  tasks:
  - name: update
    shell:
        cmd:  apt-get update
  - name: install virtual box
    shell: 
      cmd: yes | apt-get install virtualbox virtualbox-ext-pack/license select true | debconf-set-selections
  - name: install minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - name: minikube executable
    shell:
      cmd: chmod +x minikube-linux-amd64
  - name: move mini kube in bin
    shell:
      cmd: mv minikube-linux-amd64 /usr/local/bin/minikube
  - name: confirm minikube installation
    shell:
      cmd: minikube version
  - name: starting minikube
    shell:
      cmd: minikube start
      
  